(in-package cl-divsufsort)

(defconstant +stack-size+ 64)

(defstruct (stack-entry (:constructor make-stack-entry (a b c d &optional e)))
  (a 0 :type fixnum)
  (b 0 :type fixnum)
  (c 0 :type fixnum)
  (d 0 :type fixnum)
  (e 0 :type fixnum))

(defstruct (stack (:constructor make-stack ()))
  (data (make-array +stack-size+ :initial-element nil))
  (size 0 :type fixnum))

(defun stack-push (stack a b c d &optional e)
  (declare (type stack stack))
  (let ((size (stack-size stack)))
    (when (>= size +stack-size+)
      (error "Stack overflow"))
    (setf (aref (stack-data stack) size)
          (make-stack-entry a b c d e))
    (setf (stack-size stack) (1+ size))))

(defun stack-pop (stack)
  (declare (type stack stack))
  (let ((size (stack-size stack)))
    (when (<= size 0)
      (error "Stack underflow"))
    (decf (stack-size stack))
    (let ((entry (aref (stack-data stack) size)))
      (values (stack-entry-a entry)
              (stack-entry-b entry)
              (stack-entry-c entry)
              (stack-entry-d entry)
              (stack-entry-e entry)))))

(defun stack-empty-p (stack)
  (declare (type stack stack))
  (zerop (stack-size stack)))
